### ISSUE TITLE
项目文档

### ISSUE THREAD

**Issue by yangzhenyu322** [Wuqiyang312/Edge-TTS-Java#1]
大佬，可以讲一下如何集成tts到java那部分的内容吗

**Comment by Wuqiyang312** [comment]
Emma 我并不是大佬，集成tts到java那部分的内容，其实是使用okhttp3进行webSocket的调用，使用了微软的开放的 tts api 接口，本质还是一个使用 java 开发的“前端”调用界面。

**Comment by Wuqiyang312** [comment]
核心调用代码 [https://github.com/Wuqiyang312/Edge-TTS-Java/blob/main/src/main/java/webside/wuqingyuan/TTS/TTS.java](https://github.com/Wuqiyang312/Edge-TTS-Java/blob/main/src/main/java/webside/wuqingyuan/TTS/TTS.java)
